### ISSUE TITLE
Windows build fails with SWI version 8.2+

### ISSUE THREAD

**Issue by ozcanonur** [rla/node-swipl#10]
Recently updated my SWI from 8.0 to 8.2 and started getting errors while building. Tried 8.3 dev release and happens there also.
Reverting back to 8.0.3 fixes the issue.

```
error C:\Users\Onur\Desktop\Chemphoprolog\server\node_modules\swipl: Command failed.
Exit code: 1
Command: node-gyp rebuild
Arguments:
Directory: C:\Users\Onur\Desktop\Chemphoprolog\server\node_modules\swipl
Output:
C:\Users\Onur\Desktop\Chemphoprolog\server\node_modules\swipl>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "" rebuild )
gyp info it worked if it ends with ok
gyp info using node-gyp@5.1.0
gyp info using node@12.19.0 | win32 | x64
gyp info find Python using Python version 3.9.0 found at "C:\Python39\python.exe"
gyp info find VS using VS2017 (15.9.28307.1274) found at:
gyp info find VS "C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools"
gyp info find VS run with --verbose for detailed information
gyp info spawn C:\Python39\python.exe
gyp info spawn args [
gyp info spawn args   'C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\gyp\\gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'msvs',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\Onur\\Desktop\\Chemphoprolog\\server\\node_modules\\swipl\\build\\config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\Onur\\AppData\\Local\\node-gyp\\Cache\\12.19.0\\include\\node\\common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=C:\\Users\\Onur\\AppData\\Local\\node-gyp\\Cache\\12.19.0',
gyp info spawn args   '-Dnode_gyp_dir=C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp',
gyp info spawn args   '-Dnode_lib_file=C:\\\\Users\\\\Onur\\\\AppData\\\\Local\\\\node-gyp\\\\Cache\\\\12.19.0\\\\<(target_arch)\\\\node.lib',
gyp info spawn args   '-Dmodule_root_dir=C:\\Users\\Onur\\Desktop\\Chemphoprolog\\server\\node_modules\\swipl',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'C:\\Users\\Onur\\Desktop\\Chemphoprolog\\server\\node_modules\\swipl\\build',
gyp info spawn args   '-Goutput_dir=.'
gyp info spawn args ]
gyp info spawn C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin\MSBuild.exe
gyp info spawn args [
gyp info spawn args   'build/binding.sln',
gyp info spawn args   '/clp:Verbosity=minimal',
gyp info spawn args   '/nologo',
gyp info spawn args   '/p:Configuration=Release;Platform=x64'
gyp info spawn args ]
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
  libswipl.cc
  win_delay_load_hook.cc
c:\users\onur\desktop\chemphoprolog\server\node_modules\swipl\src\libswipl.cc(77): error C2664: 'int PL_get_compound_name_arity_sz(term_t,atom_t *,size_t *)': cannot convert argument 3 from 'int *' to 'size_t *' [C:\Users\Onur\Desktop\Chemphoprolog\server\node_modules\swipl\build\swipl.vcxproj]
  c:\users\onur\desktop\chemphoprolog\server\node_modules\swipl\src\libswipl.cc(77): note: Types pointed to are unrelated; conversion requires reinterpret_cast, C-style cast or function-style cast
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin\MSBuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:314:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
gyp ERR! System Windows_NT 10.0.18363
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\Onur\Desktop\Chemphoprolog\server\node_modules\swipl
gyp ERR! node -v v12.19.0
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok
```

**Comment by rla** [comment]
@ozcanonur, seems like the function `PL_get_compound_name_arity_sz` signature is changed or the compiler enforces proper type for the size argument now.

I will try to fix it. Thanks for reporting.
